"""
Prescription Parsing — Gradio UI
End-to-end pipeline: Upload → OCR → LLM Parse → Store → Search
"""

import json

import gradio as gr

from services.supabase_service import upload_file
from services.extraction_service import extract_from_file
from services.llm_service import parse_prescription, semantic_search_query
from services.database_service import (
    insert_prescription,
    insert_medical_entities,
    insert_medications,
    get_prescription_summary,
    semantic_search,
    search_by_drug,
    search_by_patient,
    search_by_diagnosis,
    search_fulltext,
    execute_raw_query,
    get_prescription_by_id,
    introspect_schema,
)


# ---------------------------------------------------------------------------
# Pipeline Logic
# ---------------------------------------------------------------------------

def process_upload(file):
    """Process an uploaded prescription file through the full pipeline."""
    if file is None:
        return "No file uploaded.", "", "", ""

    file_path = file.name if hasattr(file, "name") else file

    logs = []

    # Step 1: Upload to Supabase
    logs.append("⏳ [1/6] Uploading to Supabase Storage...")
    try:
        sb_result = upload_file(file_path)
        storage_url = sb_result["public_url"]
        logs.append(f"✅ Uploaded: {storage_url}")
    except Exception as e:
        logs.append(f"❌ Upload failed: {e}")
        return "\n".join(logs), "", "", ""

    # Step 2: Extract text
    logs.append("⏳ [2/6] Extracting text (OCR)...")
    try:
        extraction = extract_from_file(file_path)
        raw_text = extraction["text"]
        logs.append(f"✅ Extracted {len(raw_text)} chars (source: {extraction['source']})")
    except Exception as e:
        logs.append(f"❌ Extraction failed: {e}")
        return "\n".join(logs), "", "", ""

    if not raw_text.strip():
        logs.append("⚠️ No text extracted — file may be empty or unreadable.")
        return "\n".join(logs), "", "", ""

    # Step 3: Parse with LLM
    logs.append("⏳ [3/6] Parsing with Groq LLM...")
    try:
        parsed = parse_prescription(raw_text)
        if "error" in parsed:
            logs.append(f"❌ Parsing failed: {parsed['error']}")
            return "\n".join(logs), raw_text, "", ""
        logs.append("✅ Entities parsed successfully")
    except Exception as e:
        logs.append(f"❌ LLM error: {e}")
        return "\n".join(logs), raw_text, "", ""

    # Step 4: Store in DB
    logs.append("⏳ [4/6] Storing in PostgreSQL...")
    try:
        prescription_id = insert_prescription(
            file_name=sb_result["file_name"],
            storage_url=storage_url,
            file_type=sb_result["file_type"],
            raw_text=raw_text,
        )
        entity_id = insert_medical_entities(prescription_id, parsed)
        medications = parsed.get("medications", [])
        med_ids = insert_medications(entity_id, medications) if medications else []
        logs.append(f"✅ Stored — Prescription #{prescription_id}, {len(med_ids)} medications")
    except Exception as e:
        logs.append(f"❌ DB error: {e}")
        return "\n".join(logs), raw_text, json.dumps(parsed, indent=2, default=str), ""

    # Steps 5+6: Auto-generated by DB triggers
    logs.append("⏳ [5/6] Summary auto-generated by DB trigger...")
    ai_summary = get_prescription_summary(prescription_id)
    if ai_summary:
        logs.append(f"✅ Summary: {ai_summary[:100]}..." if len(ai_summary) > 100 else f"✅ Summary: {ai_summary}")
    else:
        logs.append("⚠️ Summary not generated (rate-limited — will retry on next access)")
    logs.append("✅ [6/6] Embedding auto-generated by DB trigger")

    logs.append("\n🎉 Pipeline complete!")

    # Build summary card
    summary = _build_summary(parsed, prescription_id, storage_url, ai_summary)

    return (
        "\n".join(logs),
        raw_text,
        json.dumps(parsed, indent=2, default=str),
        summary,
    )


def _build_summary(parsed: dict, rx_id: int, url: str, ai_summary: str = "") -> str:
    """Build a markdown summary of parsed prescription."""
    lines = [f"### Prescription #{rx_id}\n"]

    if parsed.get("patient_name"):
        lines.append(f"**Patient:** {parsed['patient_name']}")
    if parsed.get("patient_age"):
        lines.append(f"**Age:** {parsed['patient_age']}")
    if parsed.get("patient_gender"):
        lines.append(f"**Gender:** {parsed['patient_gender']}")
    if parsed.get("doctor_name"):
        lines.append(f"**Doctor:** {parsed['doctor_name']}")
    if parsed.get("doctor_speciality"):
        lines.append(f"**Speciality:** {parsed['doctor_speciality']}")
    if parsed.get("hospital_clinic"):
        lines.append(f"**Hospital:** {parsed['hospital_clinic']}")

    if parsed.get("diagnosis"):
        lines.append(f"\n**Diagnosis:** {', '.join(parsed['diagnosis'])}")
    if parsed.get("symptoms"):
        lines.append(f"**Symptoms:** {', '.join(parsed['symptoms'])}")

    meds = parsed.get("medications", [])
    if meds:
        lines.append(f"\n**Medications ({len(meds)}):**\n")
        lines.append("| # | Drug | Dosage | Frequency | Duration | Route | Instructions |")
        lines.append("|---|------|--------|-----------|----------|-------|-------------|")
        for i, m in enumerate(meds, 1):
            lines.append(
                f"| {i} | {m.get('drug_name', '-')} | {m.get('dosage') or '-'} | "
                f"{m.get('frequency') or '-'} | {m.get('duration') or '-'} | "
                f"{m.get('route') or '-'} | {m.get('instructions') or '-'} |"
            )

    if ai_summary:
        lines.append(f"\n**AI Summary:** {ai_summary}")

    lines.append(f"\n[View file]({url})")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Search Logic
# ---------------------------------------------------------------------------

def search_prescriptions(query: str, search_type: str) -> str:
    """Search prescriptions by various methods."""
    if not query.strip():
        return "Please enter a search query."

    try:
        if search_type == "Natural Language (AI)":
            sql = semantic_search_query(query)
            if sql.startswith("```"):
                lines = sql.split("\n")
                sql = "\n".join(lines[1:-1]) if lines[-1].strip() == "```" else "\n".join(lines[1:])
            sql = sql.strip().rstrip(";")
            results = execute_raw_query(sql)
            header = f"**Generated SQL:**\n```sql\n{sql}\n```\n\n"
        elif search_type == "Drug Name":
            results = search_by_drug(query)
            header = ""
        elif search_type == "Patient Name":
            results = search_by_patient(query)
            header = ""
        elif search_type == "Diagnosis":
            results = search_by_diagnosis(query)
            header = ""
        elif search_type == "Full Text":
            results = search_fulltext(query)
            header = ""
        elif search_type == "Semantic (Vector)":
            results = semantic_search(query)
            header = "**Semantic search** — matching by meaning against prescription summaries\n\n"
        else:
            return "Unknown search type."

        if not results:
            return header + "No results found."

        return header + f"**Found {len(results)} result(s):**\n\n```json\n{json.dumps(results, indent=2, default=str)}\n```"

    except Exception as e:
        return f"❌ Search error: {e}"


def get_prescription_detail(rx_id: str) -> str:
    """Get full details of a prescription by ID."""
    if not rx_id.strip():
        return "Enter a prescription ID."
    try:
        result = get_prescription_by_id(int(rx_id))
        if not result:
            return "Prescription not found."
        return f"```json\n{json.dumps(result, indent=2, default=str)}\n```"
    except Exception as e:
        return f"❌ Error: {e}"


def get_db_schema() -> str:
    """Return the live database schema."""
    try:
        schema = introspect_schema()
        return f"```\n{schema}\n```"
    except Exception as e:
        return f"❌ Error: {e}"


# ---------------------------------------------------------------------------
# Gradio UI
# ---------------------------------------------------------------------------

with gr.Blocks(
    title="MedSnap — Prescription Parser",
    theme=gr.themes.Soft(primary_hue="blue", secondary_hue="indigo"),
) as app:

    gr.Markdown(
        """
        # 🏥 MedSnap — Prescription Parsing Pipeline
        Upload prescription images or PDFs → OCR → AI extraction → Structured database storage → Intelligent search
        """
    )

    with gr.Tabs():
        # --- Tab 1: Upload & Process ---
        with gr.Tab("📤 Upload & Process"):
            with gr.Row():
                with gr.Column(scale=1):
                    upload_input = gr.File(
                        label="Upload Prescription (PDF / Image)",
                        file_types=[".pdf", ".png", ".jpg", ".jpeg", ".bmp", ".tiff"],
                    )
                    upload_btn = gr.Button("🚀 Process Prescription", variant="primary", size="lg")

                with gr.Column(scale=1):
                    log_output = gr.Textbox(label="Pipeline Log", lines=12, interactive=False)

            with gr.Row():
                with gr.Column():
                    raw_text_output = gr.Textbox(label="Extracted Text (OCR)", lines=10, interactive=False)
                with gr.Column():
                    parsed_output = gr.Textbox(label="Parsed Entities (JSON)", lines=10, interactive=False)

            summary_output = gr.Markdown(label="Summary")

            upload_btn.click(
                fn=process_upload,
                inputs=[upload_input],
                outputs=[log_output, raw_text_output, parsed_output, summary_output],
            )

        # --- Tab 2: Search ---
        with gr.Tab("🔍 Search Prescriptions"):
            with gr.Row():
                search_query = gr.Textbox(
                    label="Search Query",
                    placeholder="e.g. 'patients on metoprolol', 'Anita Desai', 'hypertension'...",
                    scale=3,
                )
                search_type = gr.Dropdown(
                    choices=[
                        "Natural Language (AI)",
                        "Semantic (Vector)",
                        "Drug Name",
                        "Patient Name",
                        "Diagnosis",
                        "Full Text",
                    ],
                    value="Natural Language (AI)",
                    label="Search Type",
                    scale=1,
                )
            search_btn = gr.Button("🔎 Search", variant="primary")
            search_results = gr.Markdown(label="Results")

            search_btn.click(
                fn=search_prescriptions,
                inputs=[search_query, search_type],
                outputs=[search_results],
            )

        # --- Tab 3: View Prescription ---
        with gr.Tab("📋 View Prescription"):
            with gr.Row():
                rx_id_input = gr.Textbox(label="Prescription ID", placeholder="e.g. 1")
                fetch_btn = gr.Button("Fetch", variant="primary")
            rx_detail_output = gr.Markdown(label="Prescription Details")

            fetch_btn.click(
                fn=get_prescription_detail,
                inputs=[rx_id_input],
                outputs=[rx_detail_output],
            )

        # --- Tab 4: Schema ---
        with gr.Tab("🗄️ Database Schema"):
            schema_btn = gr.Button("Show Live Schema")
            schema_output = gr.Markdown()

            schema_btn.click(fn=get_db_schema, outputs=[schema_output])


if __name__ == "__main__":
    app.launch(server_name="0.0.0.0", server_port=7860, share=False)
