"""
Prescription Parsing Pipeline — Main Orchestrator

Usage:
    python main.py upload   <file_path>          Upload, extract, parse & store
    python main.py search   <query>              Natural-language search
    python main.py drug     <drug_name>          Search by drug name
    python main.py patient  <patient_name>       Search by patient name
    python main.py diagnosis <diagnosis>         Search by diagnosis
    python main.py fulltext <query>              Full-text search on raw text
    python main.py similar  <query>              Semantic (vector) search on summaries
    python main.py get      <prescription_id>    Get full prescription details
    python main.py schema                        Print live DB schema
"""

import sys
import os
import json

from services.supabase_service import upload_file
from services.extraction_service import extract_from_file
from services.llm_service import parse_prescription, semantic_search_query
from services.database_service import (
    insert_prescription,
    insert_medical_entities,
    insert_medications,
    get_prescription_summary,
    semantic_search,
    search_by_drug,
    search_by_patient,
    search_by_diagnosis,
    search_fulltext,
    execute_raw_query,
    get_prescription_by_id,
    introspect_schema,
)


def pp(obj):
    """Pretty print JSON-serializable objects."""
    print(json.dumps(obj, indent=2, default=str))


# ---------------------------------------------------------------------------
# Pipeline
# ---------------------------------------------------------------------------

def process_prescription(file_path: str) -> dict:
    """
    Full pipeline:
    1. Upload file to Supabase Storage
    2. Extract text (PyMuPDF + PaddleOCR)
    3. Parse entities via Groq LLM (tool calling)
    4. Store everything in PostgreSQL
    5. Summary auto-generated by DB trigger (openrouter_complete)
    6. Embedding auto-generated by DB trigger (openrouter_embed)
    """
    file_path = os.path.abspath(file_path)
    if not os.path.exists(file_path):
        print(f"[ERROR] File not found: {file_path}")
        sys.exit(1)

    # Step 1 — Upload to Supabase Storage
    print("[1/6] Uploading to Supabase Storage...")
    sb_result = upload_file(file_path)
    print(f"       Uploaded: {sb_result['public_url']}")

    # Step 2 — Extract text
    print("[2/6] Extracting text...")
    extraction = extract_from_file(file_path)
    raw_text = extraction["text"]
    print(f"       Extracted {len(raw_text)} characters (source: {extraction['source']})")

    if not raw_text.strip():
        print("[WARN] No text extracted. The file might be empty or unreadable.")
        return {"error": "No text extracted"}

    # Step 3 — Parse with LLM
    print("[3/6] Parsing with Groq LLM...")
    parsed = parse_prescription(raw_text)
    print(f"       Parsed entities:")
    pp(parsed)

    if "error" in parsed:
        print(f"[ERROR] LLM parsing failed: {parsed['error']}")
        return parsed

    # Step 4 — Store in PostgreSQL
    print("[4/6] Storing in PostgreSQL...")

    prescription_id = insert_prescription(
        file_name=sb_result["file_name"],
        storage_url=sb_result["public_url"],
        file_type=sb_result["file_type"],
        raw_text=raw_text,
    )
    print(f"       Prescription ID: {prescription_id}")

    entity_id = insert_medical_entities(prescription_id, parsed)
    print(f"       Entity ID: {entity_id}")

    medications = parsed.get("medications", [])
    if medications:
        med_ids = insert_medications(entity_id, medications)
        print(f"       Medication IDs: {med_ids}")

    # Steps 5+6 — Summary + embedding are auto-generated by DB triggers
    print("[5/6] Summary auto-generated by DB trigger (openrouter_complete)...")
    summary = get_prescription_summary(prescription_id)
    if summary:
        print(f"       Summary: {summary[:120]}..." if len(summary) > 120 else f"       Summary: {summary}")
    else:
        print("       Summary not generated (rate-limited? will retry on next access)")
    print("[6/6] Embedding auto-generated by DB trigger (openrouter_embed)")

    print("\n[DONE] Prescription processed successfully!")
    return {
        "prescription_id": prescription_id,
        "entity_id": entity_id,
        "parsed": parsed,
        "summary": summary,
        "storage_url": sb_result["public_url"],
    }


def deep_search(query: str) -> list[dict]:
    """
    LLM-powered semantic search:
    1. Groq translates the natural language query into SQL using live schema
    2. Execute the generated SQL against PostgreSQL
    """
    print(f"[SEARCH] Query: {query}")
    print("[SEARCH] Generating SQL via Groq...")

    sql = semantic_search_query(query)
    # Clean markdown fences if present
    if sql.startswith("```"):
        lines = sql.split("\n")
        sql = "\n".join(lines[1:-1]) if lines[-1].strip() == "```" else "\n".join(lines[1:])
    sql = sql.strip().rstrip(";")

    print(f"[SEARCH] Generated SQL:\n{sql}\n")

    try:
        results = execute_raw_query(sql)
        print(f"[SEARCH] Found {len(results)} results")
        return results
    except Exception as e:
        print(f"[ERROR] Query execution failed: {e}")
        return []


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)

    command = sys.argv[1].lower()

    if command == "upload" and len(sys.argv) >= 3:
        result = process_prescription(sys.argv[2])
        pp(result)

    elif command == "search" and len(sys.argv) >= 3:
        query = " ".join(sys.argv[2:])
        results = deep_search(query)
        pp(results)

    elif command == "drug" and len(sys.argv) >= 3:
        results = search_by_drug(" ".join(sys.argv[2:]))
        pp(results)

    elif command == "patient" and len(sys.argv) >= 3:
        results = search_by_patient(" ".join(sys.argv[2:]))
        pp(results)

    elif command == "diagnosis" and len(sys.argv) >= 3:
        results = search_by_diagnosis(" ".join(sys.argv[2:]))
        pp(results)

    elif command == "fulltext" and len(sys.argv) >= 3:
        results = search_fulltext(" ".join(sys.argv[2:]))
        pp(results)

    elif command == "similar" and len(sys.argv) >= 3:
        query = " ".join(sys.argv[2:])
        print(f"[SEMANTIC] Embedding query and searching...")
        results = semantic_search(query)
        pp(results)

    elif command == "get" and len(sys.argv) >= 3:
        result = get_prescription_by_id(int(sys.argv[2]))
        pp(result)

    elif command == "schema":
        print(introspect_schema())

    else:
        print(__doc__)
        sys.exit(1)


if __name__ == "__main__":
    main()
